:rocket: Modal widget
KinderCorp/battleship-mobile pull request #11
Opened 2023-03-31 13:34 UTC by MaximeWrlz

2023-04-05 22:14 UTC, FlavianEng approved these changes

2023-04-06 08:28 UTC, FlavianEng requested changes
Rebase

2023-04-06 08:28 UTC, FlavianEng commented on lib/shared/Modal/modal_widget.dart
> +                          Navigator.of(context).pop();
Use AppRouter()

2023-04-07 07:55 UTC, AlexandreMichelix approved these changes

2023-04-07 08:21 UTC, DrakenLine commented on lib/shared/Modal/modal_widget.dart
> +    return TextButton(
enlever le textButton, ici on veut juste la modale

2023-04-08 07:01 UTC, FlavianEng approved these changes

2023-09-21 20:18 UTC, closed without merging

2023-09-21 20:18 UTC, DrakenLine commented
Task linked: [CU-860q3jgyw Create Modal component](https://app.clickup.com/t/860q3jgyw)