:books: Config Page
KinderCorp/battleship-mobile pull request #15
Opened 2023-04-04 21:37 UTC by AlexandreMichelix

2023-08-07 08:12 UTC, DrakenLine requested changes

2023-08-07 08:12 UTC, DrakenLine commented on lib/shared/ShareLink/share_link.dart
> +          'https://www.battleship.fr/game?id=8b1a292b05c946bc945b8d14a105dd5d');
why did you initialize the text value ? Is it not better to use `hintText` property ?

2023-08-07 08:12 UTC, DrakenLine commented on lib/shared/ShareLink/share_link.dart
> +                    Clipboard.setData(ClipboardData(text: textField.text));
why did you use `Clipboard` ?

2023-08-07 14:01 UTC, AlexandreMichelix commented on lib/shared/ShareLink/share_link.dart
> +                    Clipboard.setData(ClipboardData(text: textField.text));
to copy pasta 🍝

2023-08-07 15:59 UTC, FlavianEng commented on android/app/build.gradle
> +        minSdkVersion 19
Why this change ?

2023-08-07 15:59 UTC, FlavianEng commented on lib/pages/authentication/authentication_form.page.dart
> +                          readOnly: false,
Isn't it the default value ?

2023-08-07 15:59 UTC, FlavianEng commented on lib/pages/game_configuration/game_configuration.page.dart
> +  }
Not sure it's necessary to create this function

2023-08-07 15:59 UTC, FlavianEng commented on lib/pages/game_configuration/game_configuration.page.dart
> +                                  const ShareLinkWidget(), // Insert your widget here
Remove comment

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/Container/container_widget.dart
> +        child: SizedBox(
Shouldn't you use a [FractionallySizedBox](https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html) widget ?

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/Header/header_widget.dart
> +          content != null ? Center(child: content) : Container(),
Reverse condition, please. It's easier to your brain to think positively

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/Input/input_widget.dart
> +              if (widget.icon != null) {
Reverse condition, please. It's easier to your brain to think positively

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/Input/input_widget.dart
> +                    const EdgeInsets.symmetric(vertical: 10, horizontal: 10),
```suggestion
                    const EdgeInsets.all(10),
```

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/PlayerCard/player_card.dart
>          SizedBox(
Shouldn't you use [FractionallySizedBox widget](https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html) ?

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/ShareLink/share_link.dart
> +            SizedBox(
Shouldn't you use [FractionallySizedBox widget](https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html) ?

2023-08-07 15:59 UTC, FlavianEng commented on lib/shared/Versus/versus_widget.dart
>      return SizedBox(
Shouldn't you use [FractionallySizedBox widget](https://api.flutter.dev/flutter/widgets/FractionallySizedBox-class.html) ?

2023-08-07 17:15 UTC, AlexandreMichelix commented on android/app/build.gradle
> +        minSdkVersion 19
![image](https://github.com/KinderCorp/battleship-mobile/assets/45665886/dbf2389e-43ba-4d93-a2de-9407683e1c7b)

2023-08-07 17:21 UTC, AlexandreMichelix commented on lib/shared/Button/button_widget.dart
> +                      EdgeInsets.symmetric(horizontal: screenWidth * 0.018),
the perfect size of width button widget depending on every screen

2023-08-07 17:28 UTC, AlexandreMichelix commented on lib/pages/game_configuration/game_configuration.page.dart
> +                      padding: 20,
![image](https://github.com/KinderCorp/battleship-mobile/assets/45665886/da580d74-b901-498c-9532-293c572be938)
ContainerWidget is customized and the params is already an edge inset

2023-08-07 17:34 UTC, AlexandreMichelix commented on lib/shared/ShareLink/share_link.dart
> +            SizedBox(
In this widget no

2023-08-07 17:40 UTC, AlexandreMichelix commented on lib/shared/PlayerCard/player_card.dart
>          SizedBox(
heightfactor and widthfactor didn't work

2023-08-07 17:42 UTC, AlexandreMichelix commented on lib/shared/Versus/versus_widget.dart
>      return SizedBox(
same as before

2023-08-07 17:50 UTC, MaximeWrlz requested changes

2023-08-07 17:50 UTC, MaximeWrlz commented on lib/pages/authentication/authentication_form.page.dart
> +                          readOnly: false,
So what was the solution ?

2023-08-07 17:50 UTC, MaximeWrlz commented on lib/shared/ShareLink/share_link.dart
> +          'https://www.battleship.fr/game?id=8b1a292b05c946bc945b8d14a105dd5d');
I don't understand... if your branch is based on mine, you should have the rights default text value, which is "Creating game..."

2023-08-07 17:50 UTC, MaximeWrlz commented on macos/Flutter/ephemeral/flutter_export_environment.sh
> +export "FLUTTER_APPLICATION_PATH=/home/alexandre/Documents/Ynov/projet_fil_rouge/battleship_mobile"
The fact that the relative path is connected to your pc will not be a problem?

2023-08-07 17:50 UTC, MaximeWrlz commented on macos/Flutter/ephemeral/Flutter-Generated.xcconfig
> +FLUTTER_APPLICATION_PATH=/home/alexandre/Documents/Ynov/projet_fil_rouge/battleship_mobile
The fact that the relative path is connected to your pc will not be a problem?

2023-08-07 17:50 UTC, MaximeWrlz commented on lib/shared/ShareLink/share_link.dart
> +            SizedBox(
Maybe it could improve responsive on specific mobile screens

2023-08-07 18:29 UTC, MaximeWrlz approved these changes

2023-08-07 18:29 UTC, MaximeWrlz commented on lib/shared/Input/input_widget.dart
> +            if (widget.title == null) {
You can't do domething like this: `if (widget.title) {...}` ?

2023-08-07 19:05 UTC, AlexandreMichelix commented on lib/shared/Input/input_widget.dart
> +            if (widget.title == null) {
Conditions must have a static type of 'bool'

2023-08-08 07:13 UTC, FlavianEng commented on android/app/build.gradle
> +        minSdkVersion 19
Change flutter minSdkVersion instead -> https://www.flutterbeads.com/change-android-minsdkversion-in-flutter/?expand_article=1

2023-08-08 07:14 UTC, FlavianEng commented on lib/shared/Button/button_widget.dart
> +                      EdgeInsets.symmetric(horizontal: screenWidth * 0.018),
Based on what ?

2023-08-08 14:06 UTC, FlavianEng commented on android/app/build.gradle
> +        minSdkVersion localProperties.getProperty('flutter.minSdkVersion').toInteger()
wtf why not this :
```suggestion
        minSdkVersion flutter.minSdkVersion
```

2023-08-08 14:06 UTC, FlavianEng commented on .gitignore
> +
Check with @DrakenLine

2023-08-11 12:35 UTC, DrakenLine approved these changes

2023-08-14 08:37 UTC, merged