:rocket: Add websockets & responsive
KinderCorp/battleship-mobile pull request #20
Opened 2023-04-07 09:33 UTC by MaximeWrlz

2023-04-08 07:00 UTC, FlavianEng requested changes
Rename all "gameConfig" to "gameConfiguration" in order to write it down entirely

2023-04-08 07:00 UTC, FlavianEng commented on android/app/build.gradle
> -        minSdkVersion flutter.minSdkVersion
I think it's the source of your problem Maxime, why don't you keep this

2023-04-08 07:00 UTC, FlavianEng commented on lib/app_router.dart
> +      case RouteName.gameConfig:
```suggestion
      case RouteName.gameConfiguration:
```

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/authentication/authentication_form.page.dart
> +                              readOnly: false,
Remove this and set a default value to false in the inout widget

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
> +      TextEditingController(text: 'Waiting for new game instance...');
I think something like "Connecting to server ..." is better for the user

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
> +    while (webSocketService.instanceId.isEmpty) {
What does this part ?

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
> +    setState(() {
Wrap this setState into a function like "update .." and call it multiple times instead of duplicating the code

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
> +                margin: const [30, 50, 30, 50],
Can we use EdgeInset symmetric ?

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
> +                margin: const [0, 50, 40, 50],
Can't we use symmetric Esge insets

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
> +                title: AppLocalizations.of(context)!.start.toString(),
Unless I am mistaken, You don't need toString at the end
```suggestion
                title: AppLocalizations.of(context)!.start,
```

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/game_config/game_config.page.dart
>  class _GameConfig extends State<GameConfigPage> {
Rename this page "GameConfiguration"

2023-04-08 07:00 UTC, FlavianEng commented on lib/pages/profile/profile.dart
> +                    margin: [0, 0, 0, 0],
Why not 
```suggestion
                    margin: 0,
```

2023-04-08 07:00 UTC, FlavianEng commented on lib/services/socket.service.dart
> +    socket = IO.io('ws://10.0.2.2:8080',
Put this into an env variable

2023-04-08 07:00 UTC, FlavianEng commented on lib/services/socket.service.dart
> +      print('Connected to server with id: ${socket.id}');
Replace print with the print equivalent for debug

2023-04-08 07:00 UTC, FlavianEng commented on lib/services/socket.service.dart
> +    socket.on('disconnect', (_) {
Can't you remove the parameter?

2023-04-08 07:00 UTC, FlavianEng commented on lib/services/socket.service.dart
> +    socket.on('game-created', (response) {
Create an Enum of Events you listening and another one for events you are emitting

2023-07-27 19:38 UTC, MaximeWrlz commented on lib/pages/game_config/game_config.page.dart
> +    while (webSocketService.instanceId.isEmpty) {
`await webSocketService.connectToServer();`
Connect the app to the backend socket server when we get to the page

`await webSocketService.createGame();`
Emit the "create-game" event, to create a new game instance (cf backend game-engine)

`
while (webSocketService.instanceId.isEmpty) {
  await Future.delayed(const Duration(milliseconds: 100));
}
`
And this code prevent from delay in the generation of a new instance by the backend. As long as the back has not created the game and returned an error or a new instance, we wait.

2023-07-27 20:09 UTC, MaximeWrlz commented on lib/services/socket.service.dart
> +    socket.on('disconnect', (_) {
No I can't, socket_io_client always need a parameter, idk why

2023-07-27 20:30 UTC, MaximeWrlz commented on lib/services/socket.service.dart
> +    socket.on('game-created', (response) {
I can't too, enums in dart are like this :

`enum ListenedEvents {
  connect,
  disconnect,
  gameCreated,
}`

I can't assign a value to each "value" like this:
`enum ListenedEvents {
  CONNECT = "connect",
  DISCONNECT = "disconnect",
  GAME_CREATED = "game-created",
}`

2023-07-28 07:56 UTC, FlavianEng commented on lib/services/socket.service.dart
> +    socket.on('disconnect', (_) {
What's the name of the required parameter ?

2023-07-28 08:03 UTC, FlavianEng reviewed
It could be interesting to add `flutter lints` and `very_good_analysis`

2023-07-28 08:03 UTC, FlavianEng commented on lib/pages/home/home_page.dart
Can you uncomment the code because I don't like commented code. But set a final `isImplemented` with a false to not display this code part

2023-07-28 08:03 UTC, FlavianEng commented on lib/pages/home/home_page.dart
Also I think it could be interesting to split more your code

2023-07-28 08:03 UTC, FlavianEng commented on lib/shared/Input/input_widget.dart
Can you split you code to enhance the maintainability and the readability pls ?

2023-07-28 08:15 UTC, MaximeWrlz commented on lib/services/socket.service.dart
> +    socket.on('disconnect', (_) {
Good question, and Idk... basically, if I remove it, it throw an error and I tried to cast the event as a EventHandler but it throw an error too

2023-07-28 08:16 UTC, MaximeWrlz commented on lib/pages/home/home_page.dart
To see with @AlexandreMichelix

2023-07-28 08:16 UTC, MaximeWrlz commented on lib/shared/Input/input_widget.dart
Same, see with @AlexandreMichelix

2023-07-28 08:17 UTC, MaximeWrlz commented on lib/shared/Input/input_widget.dart
But I think this should be fix in another PR, It’s out of context here

2023-07-28 08:18 UTC, MaximeWrlz commented on .env.sample
> +API_URL=
yeah, there is a SOCKET_SERVER_URL variable now

2023-07-28 08:22 UTC, MaximeWrlz commented
> It could be interesting to add `flutter lints` and `very_good_analysis` (@FlavianEng )

Yeah, I was thinking about this yesteday, because my code wasn't formatting himself and we dont have any prettier / lint rules. Seems good to me. I'll make another branch **_(link here whare available)_** to add this and refacto some code like unimplemented commented code once this pull request is merged.

2023-07-28 09:48 UTC, FlavianEng commented
> > It could be interesting to add `flutter lints` and `very_good_analysis` (@FlavianEng )
> 
> 
> 
> Yeah, I was thinking about this yesteday, because my code wasn't formatting himself and we dont have any prettier / lint rules. Seems good to me. I'll make another branch **_(link here whare available)_** to add this and refacto some code like unimplemented commented code once this pull request is merged.
> 
> 
> 
> 

To prettier your code, use webstorm with actions on save

2023-08-01 17:44 UTC, MaximeWrlz commented
> > > It could be interesting to add `flutter lints` and `very_good_analysis` (@FlavianEng )
> > 
> > 
> > Yeah, I was thinking about this yesteday, because my code wasn't formatting himself and we dont have any prettier / lint rules. Seems good to me. I'll make another branch **_(link here whare available)_** to add this and refacto some code like unimplemented commented code once this pull request is merged.
> 
> To prettier your code, use webstorm with actions on save

Yes I know, I wanted to say that we have no rules or other, with commands like format or lint

2023-08-06 17:12 UTC, FlavianEng approved these changes

2023-08-15 14:41 UTC, DrakenLine approved these changes

2023-08-15 14:44 UTC, merged