:rocket: Modal widget & leaving game
KinderCorp/battleship-mobile pull request #33
Opened 2023-09-25 15:08 UTC by AlexandreMichelix

## Description

- Refacto code and adding modal widget and leaving game widget

## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_branch-name_**] **_summary_**
-   [x] I've added the corresponding label
-   [x] If my pull request implies some visual changes, I've linked screenshots in the description to show them
-   [x] If my pull request is linked to a task or a ticket, I've put the link in the description

--> [ClickUp](https://app.clickup.com/t/860rpd350)

[screen-capture (1).webm](https://github.com/KinderCorp/battleship-mobile/assets/45665886/8fb70682-41ee-4edf-abbb-d90051e10541)

2023-09-25 15:08 UTC, DrakenLine commented
Task linked: [CU-860rpd350 Popup confirmation leaving game](https://app.clickup.com/t/860rpd350)

2023-09-26 07:24 UTC, DrakenLine requested changes

2023-09-26 08:01 UTC, MaximeWrlz commented on lib/shared/Button/button_widget.dart
Yes but it's not a problem, it's on another branch, so it's okay for me

2023-09-26 08:05 UTC, MaximeWrlz commented on lib/shared/Button/button_widget.dart
I'll make some changements here in a future PR (that will have to be merged before the exam).

2023-09-26 08:13 UTC, AlexandreMichelix commented on lib/shared/ChoiceModal/choice_modal.dart
> +                  const SizedBox(width: 60),
Because the title was not in the center of the screen modal due to de close button

2023-09-26 08:27 UTC, MaximeWrlz commented on lib/shared/ChoiceModal/choice_modal.dart
> +                  const SizedBox(width: 60),
J'ai ausi la solution pour ça, il faut utiliser un stack mais c'est un peu tricky, mais ça permet d'éviter les container ou sizedBix vides

2023-09-26 08:30 UTC, MaximeWrlz commented on lib/shared/ChoiceModal/choice_modal.dart
> +            Container(
This is the very clear line just below the header, not sure we can do it with a border I think

2023-09-26 08:36 UTC, MaximeWrlz commented on lib/shared/ChoiceModal/choice_modal.dart
> +                        Padding(
What if you remove each button padding and use MainAxisAlignment.spaceEvenly or MainAxisAlignment.spaceAround  in your row ?

2023-09-26 08:41 UTC, AlexandreMichelix commented on lib/shared/ChoiceModal/choice_modal.dart
> +                        Padding(
it works

2023-09-26 13:05 UTC, DrakenLine approved these changes

2023-09-26 13:05 UTC, merged